name: validate-commit

on: push

jobs:
  validate-commits:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v1
      - name: Commitsar check
        uses: docker://aevea/commitsar
